# Generated by Django 3.2.4 on 2021-06-19 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schoolname',
            new_name='School',
        ),
    ]
