# Generated by Django 3.2.4 on 2021-06-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_level_parent_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='name',
            new_name='school',
        ),
    ]
