# Generated by Django 3.2.4 on 2021-06-21 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_auto_20210621_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.school'),
        ),
    ]
