# Generated by Django 3.2.4 on 2021-06-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_school_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
