# Generated by Django 3.2.4 on 2021-06-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0011_delete_useraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='grade',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='parent',
            new_name='parent_name',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school',
            new_name='school_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student',
            new_name='student_name',
        ),
    ]
