# Generated by Django 3.2.4 on 2021-06-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0015_auto_20210624_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='parent',
        ),
        migrations.AddField(
            model_name='school',
            name='parent',
            field=models.ManyToManyField(to='schoolapp.Parent'),
        ),
        migrations.RemoveField(
            model_name='school',
            name='student',
        ),
        migrations.AddField(
            model_name='school',
            name='student',
            field=models.ManyToManyField(to='schoolapp.Student'),
        ),
    ]
