# Generated by Django 3.2.4 on 2021-06-25 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schoolapp', '0019_auto_20210625_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nick_name',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=125, null=True)),
                ('last_name', models.CharField(max_length=125, null=True)),
                ('children', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
