# Generated by Django 3.2.4 on 2021-06-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0020_auto_20210625_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='children',
        ),
        migrations.AddField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(to='schoolapp.Student'),
        ),
    ]
